[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.0.0",
    "huggingface-hub>=0.34.4",
    "jupyterlab>=4.4.5",
    "neo4j>=5.28.2",
    "openai>=1.99.9",
    "python-dotenv>=1.1.1",
    "tiktoken>=0.11.0",
    "tqdm>=4.67.1",
]
